// SYNC
export const FILL_POSTS = 'FILL_POSTS';
export const CREATE_POST = 'CREATE_POST';

//ASYNC
export const FETCH_POST_ASYNC = 'FETCH_POST_ASYNC';
export const CREATE_POST_ASYNC = 'CREATE_POST_ASYNC';
